import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { getConfig } from '../utils/config.js';
import { getLocalRegistry, type ComponentMeta } from '../registry/client.js';

// Category to source subdirectory mapping
const CATEGORY_DIR: Record<string, string> = {
  layout: 'layout',
  typography: 'typography',
  input: 'input',
  selection: 'selection',
  data: 'data',
  feedback: 'feedback',
  navigation: 'navigation',
  overlays: 'overlays',
  forms: 'forms',
  utility: 'utility',
  charts: 'charts',
  templates: 'templates',
};

export async function add(args: string[]): Promise<void> {
  if (args.length === 0) {
    console.error('\x1b[31mError:\x1b[0m Please specify a component name.');
    console.error('  Example: \x1b[36mnpx termui add spinner\x1b[0m\n');
    process.exit(1);
  }

  const cwd = process.cwd();
  const config = getConfig(cwd);
  const registry = getLocalRegistry();

  for (const componentName of args) {
    const meta = registry.components[componentName];

    if (!meta) {
      console.error(`\x1b[31m✗\x1b[0m Component not found: \x1b[1m${componentName}\x1b[0m`);
      console.error(`  Run \x1b[36mnpx termui list\x1b[0m to see available components.\n`);
      continue;
    }

    await installComponent(meta, config.componentsDir, cwd, registry);
  }
}

async function installComponent(
  meta: ComponentMeta,
  componentsDir: string,
  cwd: string,
  registry: ReturnType<typeof getLocalRegistry>
): Promise<void> {
  console.log(`\x1b[35m◆\x1b[0m Adding \x1b[1m${meta.name}\x1b[0m...`);

  // Install peer components first
  if (meta.peerComponents) {
    for (const peer of meta.peerComponents) {
      const peerMeta = registry.components[peer];
      if (peerMeta) {
        await installComponent(peerMeta, componentsDir, cwd, registry);
      }
    }
  }

  // Resolve output directory
  const categoryDir = CATEGORY_DIR[meta.category] ?? meta.category;
  const outDir = join(cwd, componentsDir, categoryDir);

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  // For now, write a stub file since we don't have a live registry
  // In production this would fetch from registry.termui.dev
  for (const fileName of meta.files) {
    const outPath = join(outDir, fileName);
    if (existsSync(outPath)) {
      console.log(`  \x1b[33m~\x1b[0m ${fileName} already exists, skipping`);
      continue;
    }

    const stub = generateStub(meta, fileName);
    writeFileSync(outPath, stub, 'utf-8');
    console.log(`  \x1b[32m✓\x1b[0m Created ${outPath.replace(cwd + '/', '')}`);
  }

  console.log(`\x1b[32m✓\x1b[0m Added \x1b[1m${meta.name}\x1b[0m\n`);
}

function generateStub(meta: ComponentMeta, fileName: string): string {
  const componentName = fileName.replace('.tsx', '').replace('.ts', '');
  return `// ${meta.name} — ${meta.description}
// Generated by: npx termui add ${meta.name}
// Docs: https://termui.dev/components/${meta.name}
//
// This is a stub. Install @termui/components for the full implementation:
//   npm install @termui/components

export { ${componentName} } from '@termui/components';
`;
}
