import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { getConfig } from '../utils/config.js';
import { getLocalRegistry } from '../registry/client.js';

// ANSI color helpers
const c = {
  red: (s: string) => `\x1b[31m${s}\x1b[0m`,
  green: (s: string) => `\x1b[32m${s}\x1b[0m`,
  cyan: (s: string) => `\x1b[36m${s}\x1b[0m`,
  bold: (s: string) => `\x1b[1m${s}\x1b[0m`,
  dim: (s: string) => `\x1b[2m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
};

const CATEGORY_DIR: Record<string, string> = {
  layout: 'layout',
  typography: 'typography',
  input: 'input',
  selection: 'selection',
  data: 'data',
  feedback: 'feedback',
  navigation: 'navigation',
  overlays: 'overlays',
  forms: 'forms',
  utility: 'utility',
  charts: 'charts',
  templates: 'templates',
};

function generateStubContent(componentName: string, metaName: string, description: string): string {
  return `// ${metaName} — ${description}
// Generated by: npx termui add ${metaName}
// Docs: https://termui.dev/components/${metaName}
//
// This is a stub. Install @termui/components for the full implementation:
//   npm install @termui/components

export { ${componentName} } from '@termui/components';
`;
}

function computeDiff(original: string, updated: string, fileName: string): string {
  const origLines = original.split('\n');
  const updLines = updated.split('\n');

  const lines: string[] = [];
  lines.push(c.bold(`--- a/${fileName}`));
  lines.push(c.bold(`+++ b/${fileName}`));

  const maxLen = Math.max(origLines.length, updLines.length);
  let hasDiff = false;

  for (let i = 0; i < maxLen; i++) {
    const origLine = origLines[i];
    const updLine = updLines[i];

    if (origLine === undefined) {
      lines.push(c.green(`+  ${updLine}`));
      hasDiff = true;
    } else if (updLine === undefined) {
      lines.push(c.red(`-  ${origLine}`));
      hasDiff = true;
    } else if (origLine !== updLine) {
      lines.push(c.red(`-  ${origLine}`));
      lines.push(c.green(`+  ${updLine}`));
      hasDiff = true;
    } else {
      lines.push(c.dim(`   ${origLine}`));
    }
  }

  if (!hasDiff) {
    return '';
  }

  return lines.join('\n');
}

export async function diff(args: string[]): Promise<void> {
  if (args.length === 0) {
    console.error(c.red('Error:') + ' Please specify a component name.');
    console.error('  Example: ' + c.cyan('npx termui diff spinner') + '\n');
    process.exit(1);
  }

  const cwd = process.cwd();
  const config = getConfig(cwd);
  const registry = getLocalRegistry();

  for (const componentName of args) {
    const meta = registry.components[componentName];

    if (!meta) {
      console.error(c.red('✗') + ` Component not found: ${c.bold(componentName)}`);
      console.error(`  Run ${c.cyan('npx termui list')} to see available components.\n`);
      continue;
    }

    const categoryDir = CATEGORY_DIR[meta.category] ?? meta.category;
    const outDir = join(cwd, config.componentsDir, categoryDir);

    console.log(`\n${c.bold(c.cyan(`Diff: ${meta.name}`))}\n`);

    let hasAnyDiff = false;

    for (const fileName of meta.files) {
      const filePath = join(outDir, fileName);

      if (!existsSync(filePath)) {
        console.log(c.yellow(`  ~ ${fileName}: file not found locally (not installed)`));
        continue;
      }

      const localContent = readFileSync(filePath, 'utf-8');
      const componentName2 = fileName.replace('.tsx', '').replace('.ts', '');
      const expectedContent = generateStubContent(componentName2, meta.name, meta.description);

      const diffOutput = computeDiff(localContent, expectedContent, fileName);

      if (!diffOutput) {
        console.log(c.green(`  ✓ ${fileName}: up to date`));
      } else {
        hasAnyDiff = true;
        console.log(`  ${c.yellow('~')} ${fileName}:`);
        console.log(diffOutput);
      }
    }

    if (!hasAnyDiff) {
      console.log(c.green(`\n✓ ${meta.name} is up to date.\n`));
    } else {
      console.log(
        c.yellow(
          `\n~ ${meta.name} has differences. Run 'npx termui update ${meta.name}' to update.\n`
        )
      );
    }
  }
}
