import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { getConfig } from '../utils/config.js';
import { getLocalRegistry, type ComponentMeta } from '../registry/client.js';

// ANSI color helpers
const c = {
  red: (s: string) => `\x1b[31m${s}\x1b[0m`,
  green: (s: string) => `\x1b[32m${s}\x1b[0m`,
  cyan: (s: string) => `\x1b[36m${s}\x1b[0m`,
  bold: (s: string) => `\x1b[1m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
  magenta: (s: string) => `\x1b[35m${s}\x1b[0m`,
};

const CATEGORY_DIR: Record<string, string> = {
  layout: 'layout',
  typography: 'typography',
  input: 'input',
  selection: 'selection',
  data: 'data',
  feedback: 'feedback',
  navigation: 'navigation',
  overlays: 'overlays',
  forms: 'forms',
  utility: 'utility',
  charts: 'charts',
  templates: 'templates',
};

function generateStub(meta: ComponentMeta, fileName: string): string {
  const componentName = fileName.replace('.tsx', '').replace('.ts', '');
  return `// ${meta.name} — ${meta.description}
// Generated by: npx termui update ${meta.name}
// Docs: https://termui.dev/components/${meta.name}
//
// This is a stub. Install @termui/components for the full implementation:
//   npm install @termui/components

export { ${componentName} } from '@termui/components';
`;
}

async function updateComponent(
  meta: ComponentMeta,
  componentsDir: string,
  cwd: string,
  registry: ReturnType<typeof getLocalRegistry>
): Promise<void> {
  console.log(`${c.magenta('◆')} Updating ${c.bold(meta.name)}...`);

  // Update peer components first
  if (meta.peerComponents) {
    for (const peer of meta.peerComponents) {
      const peerMeta = registry.components[peer];
      if (peerMeta) {
        await updateComponent(peerMeta, componentsDir, cwd, registry);
      }
    }
  }

  const categoryDir = CATEGORY_DIR[meta.category] ?? meta.category;
  const outDir = join(cwd, componentsDir, categoryDir);

  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  for (const fileName of meta.files) {
    const outPath = join(outDir, fileName);
    const existed = existsSync(outPath);

    const stub = generateStub(meta, fileName);
    writeFileSync(outPath, stub, 'utf-8');

    const action = existed ? c.yellow('↺') : c.green('✓');
    const verb = existed ? 'Updated' : 'Created';
    console.log(`  ${action} ${verb} ${outPath.replace(cwd + '/', '')}`);
  }

  console.log(`${c.green('✓')} Updated ${c.bold(meta.name)}\n`);
}

export async function update(args: string[]): Promise<void> {
  if (args.length === 0) {
    console.error(c.red('Error:') + ' Please specify a component name.');
    console.error('  Example: ' + c.cyan('npx termui update spinner') + '\n');
    process.exit(1);
  }

  const cwd = process.cwd();
  const config = getConfig(cwd);
  const registry = getLocalRegistry();

  for (const componentName of args) {
    const meta = registry.components[componentName];

    if (!meta) {
      console.error(c.red('✗') + ` Component not found: ${c.bold(componentName)}`);
      console.error(`  Run ${c.cyan('npx termui list')} to see available components.\n`);
      continue;
    }

    await updateComponent(meta, config.componentsDir, cwd, registry);
  }
}
