export const nordTheme = {
    name: 'nord',
    colors: {
        primary: '#88C0D0',
        primaryForeground: '#2E3440',
        secondary: '#4C566A',
        secondaryForeground: '#ECEFF4',
        accent: '#81A1C1',
        accentForeground: '#2E3440',
        success: '#A3BE8C',
        successForeground: '#2E3440',
        warning: '#EBCB8B',
        warningForeground: '#2E3440',
        error: '#BF616A',
        errorForeground: '#ECEFF4',
        info: '#5E81AC',
        infoForeground: '#ECEFF4',
        background: '#2E3440',
        foreground: '#ECEFF4',
        muted: '#3B4252',
        mutedForeground: '#4C566A',
        border: '#4C566A',
        focusRing: '#88C0D0',
        selection: '#3B4252',
        selectionForeground: '#ECEFF4',
    },
    spacing: {
        0: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        6: 6,
        8: 8,
    },
    typography: {
        bold: true,
        sm: 'dim',
        base: '',
        lg: 'bold',
        xl: 'bold',
    },
    border: {
        style: 'round',
        color: '#4C566A',
        focusColor: '#88C0D0',
    },
};
//# sourceMappingURL=nord.js.map