import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

export interface TermUIConfig {
  version: string;
  componentsDir: string;
  registry: string;
  theme: string;
}

const DEFAULT_CONFIG: TermUIConfig = {
  version: '1.0.0',
  componentsDir: './components/ui',
  registry: 'https://arindam200.github.io/termui',
  theme: 'default',
};

// Search order: .json first (writable), then .ts/.js (read-only; generated by create/init)
const CONFIG_CANDIDATES = [
  { file: 'termui.config.json', format: 'json' as const },
  { file: 'termui.config.ts', format: 'ts' as const },
  { file: 'termui.config.js', format: 'js' as const },
];

export function readConfig(cwd = process.cwd()): TermUIConfig | null {
  for (const { file, format } of CONFIG_CANDIDATES) {
    const configPath = join(cwd, file);
    if (!existsSync(configPath)) continue;

    if (format === 'json') {
      try {
        const raw = readFileSync(configPath, 'utf-8');
        return JSON.parse(raw) as TermUIConfig;
      } catch {
        return null;
      }
    }

    // TS/JS: extract plain object fields with a regex — no eval, no import()
    // Handles: export default { key: 'value', ... }
    try {
      const src = readFileSync(configPath, 'utf-8');
      const config: Partial<TermUIConfig> = {};
      const pairs: [keyof TermUIConfig, RegExp][] = [
        ['version', /\bversion\s*:\s*['"]([^'"]+)['"]/],
        ['componentsDir', /\bcomponentsDir\s*:\s*['"]([^'"]+)['"]/],
        ['registry', /\bregistry\s*:\s*['"]([^'"]+)['"]/],
        ['theme', /\btheme\s*:\s*['"]([^'"]+)['"]/],
      ];
      for (const [key, re] of pairs) {
        const m = re.exec(src);
        if (m?.[1]) config[key] = m[1];
      }
      if (Object.keys(config).length === 0) return null;
      return { ...DEFAULT_CONFIG, ...config };
    } catch {
      return null;
    }
  }
  return null;
}

/**
 * Write config. Always writes to termui.config.json.
 * If the project only has a .ts config, the JSON file is created alongside it
 * so future CLI commands can update it without touching the TS source.
 */
export function writeConfig(config: TermUIConfig, cwd = process.cwd()): void {
  const configPath = join(cwd, 'termui.config.json');
  writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
}

export function getConfig(cwd = process.cwd()): TermUIConfig {
  return readConfig(cwd) ?? DEFAULT_CONFIG;
}
