export {
  renderToString,
  createTestRenderer,
  screen,
  fireEvent,
  waitFor,
  stripVolatile,
  normalizeAnsi,
  toMatchSnapshot,
  updateSnapshot,
  setupTerminalMatchers,
  testCLI,
  mockRegistry,
  mockFS,
} from '@termui/testing';
export type {
  TestRenderer,
  RenderResult,
  FireEventOptions,
  WaitForOptions,
  CLIResult,
  TestCLIOptions,
  MockRegistryComponent,
  MockRegistryHandle,
  MockFSHandle,
  TerminalMatchers,
} from '@termui/testing';
